### ISSUE TITLE
Firefox启用DuckDuckGo Privacy Essentials后无法显示www.v2ray.com左侧的导航列表

### ISSUE THREAD

**Issue by vulgarchorus** [v2ray/manual#232]
Firefox64.0在启用DuckDuckGo Privacy Essentials（verson 2018.6.28)这个add-on后，不能显示页面左侧`<nav></nav>`中的导航目录，浏览器截图如下：

**Enabled:**
![image](https://user-images.githubusercontent.com/33189168/51789485-44051080-21c4-11e9-8745-49284d79fdbc.png)

**Disabled:**
![image](https://user-images.githubusercontent.com/33189168/51789527-81699e00-21c4-11e9-8061-d144714c4422.png)

如果没有左侧导航链接，则不能查看网站中除index.html外任何内容。

**Comment by VictoriaRaymond** [comment]
应该是CloudFlare的Rocket Loader导致的，已经修复，等CDN刷新。
