### ISSUE TITLE
"servers"/"response" 这两对象在配置手册未找到，是何种用途？小白一枚，勿见笑

### ISSUE THREAD

**Issue by George-taoqi** [v2ray/manual#241]
"settings": {
        "vnext": [  
        ],
        "servers": null,   //用途不知
        "response": null  //用途不知

**Comment by tjLEIIQM3** [comment]
当outbound协议为socks或shadowsocks会使用到servers。
使用blackhole协议时会涉及到response。
不过他们的值为null时，是不起作用的。
这大概是你所使用的客户端生成配置的算法问题，导致留了两个尾巴。
