### ISSUE TITLE
http 代理 settings 中的用户等级应与其他协议的用户等级统一为 level　

### ISSUE THREAD

**Issue by aketr** [v2ray/manual#243]
现在文档中除 http settings 中的用户等级设定外其他协议均为 level，而前者仍为 userlevel，可能会让用户造成混淆，希望能统一

见 https://github.com/v2ray/v2ray-core/blob/master/infra/conf/http.go#L17
https://github.com/v2ray/manual/search?q=userlevel&unscoped_q=userlevel

**Comment by nicholascw** [comment]
Open an issue under v2ray-core see if they would like to change it.
