### ISSUE TITLE
关于 捐助页

### ISSUE THREAD

**Issue by selay01** [v2ray/manual#264]
https://www.v2ray.com/chapter_00/02_donate.html
对于单次捐赠的价值超过 $50，您可以从如下选项中指定一项:
    为期一个月的首页广告 (您的名字，或 Logo);
    按您的喜好修改我们的代码。限制：不可影响用户使用，不可影响文档。您的修改将保留一个月。

**_关于修改代码，应增加流程说明，以及对 匿名和安全 的影响的信息。_**

**Comment by kslr** [comment]
我们正在评估其影响

**Comment by nicholascw** [comment]
#266 
All requests in regards of commercial or security are paused.
