### ISSUE TITLE
https to http redirect for v2ray.com

### ISSUE THREAD

**Issue by nickgnazzo** [v2ray/manual#278]
Hi there!

I was working on something for a project that uses v2ray and noticed there's an issue with the v2ray.com site when redirecting from the root domain (v2ray.com) to the www domain (www.v2ray.com).

When using a go package that uses v2ray.com/core as one of its dependencies, the "go get" command will fail because of this error:

`package v2ray.com/core: unrecognized import path "v2ray.com/core" (https fetch: Get http://www.v2ray.com/core/?go-get=1: redirected from secure URL https://v2ray.com/core?go-get=1 to insecure URL http://www.v2ray.com/core/?go-get=1)`

Upon closer inspection, it appears when trying to resolve v2ray.com/core, the server returns an HTTP 301 status. However, it does not seem to preserve the protocol (https in this case) when sending the "location" header. As you can see here (output from curl command):

```
root@server:~# curl -i https://v2ray.com/core?go-get=1
HTTP/1.1 301 Moved Permanently
Date: Sat, 07 Sep 2019 20:09:37 GMT
Content-Type: text/html
Transfer-Encoding: chunked
Connection: keep-alive
Set-Cookie: __cfduid=d4b75de6453f9bd74437d656e18ef702d1567886977; expires=Sun, 06-Sep-20 20:09:37 GMT; path=/; domain=.v2ray.com; HttpOnly; Secure
Location: http://www.v2ray.com/core/?go-get=1
Access-Control-Allow-Origin: *
Expires: Sat, 07 Sep 2019 20:18:36 GMT
Cache-Control: max-age=7200
X-Proxy-Cache: MISS
X-GitHub-Request-Id: D410:1035:207ED:2FFAB:5D73F47C
CF-Cache-Status: HIT
Age: 6661
Strict-Transport-Security: max-age=15552000; includeSubDomains; preload
X-Content-Type-Options: nosniff
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Server: cloudflare
CF-RAY: 512b524a5f88c1cf-IAD

<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
root@server:~#
```

The "Location" header returned by the server is redirecting me to http://www.v2ray.com even though the original request had https in the URL.

Oddly enough, this does not appear to be the behavior when there is a trailing slash in the URL. In the above example, I used `https://v2ray.com/core?go-get=1`. But when I change the request URL to `https://v2ray.com/core/?go-get=1`, the server preserves the "https" part of the URL when returning the Location header:

```
root@server:~# curl -i https://v2ray.com/core/?go-get=1
HTTP/1.1 301 Moved Permanently
Date: Sat, 07 Sep 2019 20:12:30 GMT
Content-Type: text/html
Transfer-Encoding: chunked
Connection: keep-alive
Set-Cookie: __cfduid=d95cf6fce5dfb951a5b098f78559cc7d21567887150; expires=Sun, 06-Sep-20 20:12:30 GMT; path=/; domain=.v2ray.com; HttpOnly; Secure
Location: https://www.v2ray.com/core/index.html?go-get=1
CF-Cache-Status: HIT
Age: 399
Strict-Transport-Security: max-age=15552000; includeSubDomains; preload
X-Content-Type-Options: nosniff
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Server: cloudflare
CF-RAY: 512b5680d87523e8-IAD

<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.10.3</center>
</body>
</html>
root@server:~#
```

**Comment by kslr** [comment]
Can`t solve the problem now, you can try go 1.3.1

**Comment by nickgnazzo** [comment]
After looking around a little more, I think this is actually a GitHub Pages redirection quirk. Since v2ray looks like it's hosted on github.io, it appears to have the same behavior shown here in this issue:

https://github.com/golang/go/issues/32071

In one of the comments on that thread, the GitHub support team mentions this redirection logic as a known issue:

> There is an interesting clue in [isaacs/github#289 (comment)](https://github.com/isaacs/github/issues/289#issuecomment-430941254):
> 
> > GitHub Support wrote:
> > > This redirection quirk that you've discovered is a known issue, and relates to trailing slashes and how our redirects work at the moment. Making a request to a URL without a trailing slash will cause redirections to run in this order:
> > > request to original URL
> > > 301 to HTTPS version of original URL
> > > 301 to HTTP version with added trailing slash
> > > 301 to HTTPS version with added trailing slash
> > > Always including the trailing slash will allow you to skip the extra redirects:
> > > request to URL with trailing slash
> > > 301 to HTTPS version of original URL
> > > We have an issue open internally to hopefully improve this situation, but investigations have demonstrates that it is a non-trivial issue to resolve.



Github appeared to deploy a fix that worked for the "googlemaps" github page (on github.io), but this fix seems to have not been deployed to v2ray.com (or perhaps the group of servers v2ray belongs to).

I've emailed Github support about the issue and will post and update if/when they respond.

**Comment by nicholascw** [comment]
We currently can do nothing on the server-side, domain, or hosting changes, (Maybe) not even the repository settings, due to the organization/project owner is inactive in the past months. Consider check out @v2fly and v2fly.org could fix the issue, at least on that side there are an active community with full permissions on those mentioned above. Sorry for the inconvenience.
