### ISSUE TITLE
中文文档中DNS部分有误

### ISSUE THREAD

**Issue by ghost** [v2ray/manual#286]
zh_cn/chapter_02/04_dns.md
纯字符串: 当此字符串匹配目标域名中任意部分，该规则生效。当此域名完整匹配目标域名时，该规则生效。例如"v2ray.com"匹配"v2ray.com"但不匹配"www.v2ray.com"。

英文文档倒是对的

**Comment by kslr** [comment]
你能详细描述一下吗

**Comment by nicholascw** [comment]
当前版本中英文表述一致 故关闭。
