### ISSUE TITLE
建议在神一般的工具们里，收录mellow,这是一个横跨MacOS,Linux,Windows的工具

### ISSUE THREAD

**Issue by yoheRabit** [v2ray/manual#290]
我这MacOS Catalina上使用良好,它解决了v2rayU,v2rayX这样的工具无法在pac模式下对一个应用发出的请求进行分流，如mail。尽管它还很新，但它值得尝试以及它将越来越好。每个稍懂v2ray JSON配置的人都能很好得使用它。

**Comment by kslr** [comment]
Welcome PR
