### ISSUE TITLE
New Cross-Platform GUI Client for V2Ray

### ISSUE THREAD

**Issue by Dr-Incognito** [v2ray/manual#311]
I develop a new GUI client for V2Ray, named [V2Ray Desktop](https://github.com/Dr-Incognito/V2Ray-Desktop).
Please consider adding it to [神一样的工具们](https://www.v2ray.com/awesome/tools.html).

**Comment by Dr-Incognito** [comment]
@kslr
Both the two requirements are ridiculous!
 
1. The name of all tools contains "V2Ray" (e.g., V2RayU, V2RayX, V2RayN).
2. Not all tools have more than 300 stars (e.g., [V2RayC](https://github.com/gssdromen/V2RayC), [V2RayN](https://github.com/v2ray/V2RayN)). But they are still on [this page](https://v2ray.com/awesome/tools.html).

**Comment by Dr-Incognito** [comment]
There are also a empty project, named Qv2ray, containing only 1 star due to the migration of the project.

**Comment by kslr** [comment]
"V2Ray Desktop" "V2Ray" Is a separate vocabulary, like "Core", this is not allowed. You can try combining new names, but not by themselves.

**Comment by Dr-Incognito** [comment]
@kslr 
- How about the name "V2RayDesktop"?
- What's your response to the requirements of 300 stars?

**Comment by kslr** [comment]
no problem with this name

**Comment by Dr-Incognito** [comment]
Fine.
Don't you think it stupid to require a new project having more than 300 stars?
[V2RayC](https://github.com/gssdromen/V2RayC) and [V2RayA](https://github.com/mzz2017/V2RayA) both have 93 stars. However, only V2RayC is on [this page](https://www.v2ray.com/awesome/tools.html).

**Comment by mzz2017** [comment]
> Fine.
> Don't you think it stupid to require a new project to have more than 300 stars?
> [V2RayC](https://github.com/gssdromen/V2RayC) and [V2RayA](https://github.com/mzz2017/V2RayA) both have 93 stars. However, only V2RayC is on [this page](https://www.v2ray.com/awesome/tools.html).

Be patient.
Judging a tool with the number of star as it's standard is not absolutely reasonable, but I think a tool should be at least complete and stable.
Some tools in that page because they have been there for a long time and the standard that time was different from now.
But since the standard is changed, how about delete them from the page?

**Comment by Dr-Incognito** [comment]
@mzz2017 
I agree with you.
If a tool have been released for a long time and does not have more than 300 stars, I think it may not be a good tool.
Removing it from that page should be reasonable.
