### ISSUE TITLE
邮件地址不存在

### ISSUE THREAD

**Issue by hwdef** [v2ray/manual#312]
开发人员手册->加入方式
中的邮箱`love@v2ray.com`不存在，无法向其发送邮件。

**Comment by hwdef** [comment]
![image](https://user-images.githubusercontent.com/13084946/73752626-3e111a80-479c-11ea-956b-37f26deef20c.png)

**Comment by kslr** [comment]
你好

目前只有V2Fly的团队可以加入，要求是3个已经合并的PR（不限仓库），当你准备好的时候，可以AT我。

**Comment by hwdef** [comment]
那不考虑一下移除这个邮件地址？
