### ISSUE TITLE
關於手冊項目的維護工作

### ISSUE THREAD

**Issue by dctxmei** [v2ray/manual#319]
@kslr 目前，

* https://www.v2ray.com/
* https://www.v2fly.org/

兩個站點的內容並不一致，這給維護工作帶來困難。

手冊項目究竟是以 [v2ray/manual](https://github.com/v2ray/manual) 還是 [v2fly/manual](https://github.com/v2fly/manual) 為準呢？

**Comment by kslr** [comment]
理论上来说，目前fly会多一个多配置的指南以及actions配置。
其他变化主要还是在ray上面
