### ISSUE TITLE
統一中文文案排版

### ISSUE THREAD

**Issue by dctxmei** [v2ray/manual#320]
@kslr 目前，無論是手冊還是新白話文教程，由於每個人的寫作風格不同，導致協同維護的結果顯得非常糟糕，我提議使用「[中文文案排版指北](https://github.com/sparanoid/chinese-copywriting-guidelines)」作為標準，以提高內容質量。

**Comment by kslr** [comment]
没问题，可以在CI中添加检查和处理

**Comment by dctxmei** [comment]
在 CI 中添加了 [lint-md-cli](https://github.com/hustcc/lint-md/tree/master/packages/lint-md-cli)，以處理 Markdown 文件中的中文文案基本排版問題。

但對於多餘的空格、重複使用的標點符號、全形和半形符號的使用、專有名詞使用正確的大小寫等問題，仍然需要人工校驗。

**Comment by kslr** [comment]
没问题，稍后我会将修改同步到ray
