### ISSUE TITLE
请求更新配置文档

### ISSUE THREAD

**Issue by ls-zhu** [v2ray/manual#325]
目前配置文档已经和config.json字段不完全匹配了

**Comment by hikigaya58** [comment]
神一样的工具们里面Qv2ray的网址也失效了。代码里是更新了的，是gitbook没有重新生成吗？

**Comment by kslr** [comment]
> 神一样的工具们里面Qv2ray的网址也失效了。代码里是更新了的，是gitbook没有重新生成吗？

    ray 不再更新
