### ISSUE TITLE
一段JSON有误

### ISSUE THREAD

**Issue by XYenon** [v2ray/manual#35]
chapter_03/01_effective.html中“VMess ID” 数量下面的JSON有误，正确写法应该是

"settings": {
  "clients": [{
    "id": "3b129dec-72a3-4d28-aeee-028a0fe86e22",
    "alterId": 100
  },
  {
    "id": "8f62a287-e80a-441f-9f28-affc9fb6c572",
    "alterId": 1000
  }]
}

**Comment by DarienRaymond** [comment]
谢谢
