### ISSUE TITLE
推荐的第三方客户端V2RayN整个项目消失了

### ISSUE THREAD

**Issue by Sherman-Liu** [v2ray/manual#45]
https://www.v2ray.com/chapter_01/3rd_party.html 中，推荐的新手友好客户端V2RayN的Github项目不存在了： https://github.com/v2ray/v2rayN ，显示404，请问发生了什么事，是停止开发了吗？还是单纯的链接错误？

**Comment by DarienRaymond** [comment]
此项目上已停止更新，代码已恢复，但目前没有开发者继续维护。

**Comment by nicholascw** [comment]
已备注停止维护并下移。
