### ISSUE TITLE
速度测试中的配置有错误

### ISSUE THREAD

**Issue by NanerLee** [v2ray/manual#55]
**zh_cn/chapter_01/speed.md** 中的 **测试 V2Ray 的连接速度** 小节中,  配置中缺少下面一行:
`"listen": "127.0.0.1",`

否则的话, 客户端启动 iperf 的 的命令应为:
`./iperf3 -c 0.0.0.0 -p 8888`

**Comment by nicholascw** [comment]
已检查相关章节并未发现问题.
