### ISSUE TITLE
Protobuf 配置文档更新

### ISSUE THREAD

**Issue by ghost** [v2ray/manual#56]
请着手更新v2ray-core项目的Protobuf 配置文档。以便v2ray客户端的更新支持。

请在文档中说明v2ray-core项目对正在使用的JSON配置的处理方式：
v2ray-core项目后续版本是如何对JSON配置文件支持。是不是改为采用第三方程序(如v2ctl)，把JSON格式配置转换为v2ray可执行文件可以使用的Protobuf格式。
v2ray-core项目将来会不会完全废弃JSON配置文件，只单独使用Protobuf配置文件。包括v2ctl也不再转换JSON格式到Protobuf格式。

**Comment by kslr** [comment]
目前不会废弃JSON配置
