### ISSUE TITLE
Potential install script command improvement?

### ISSUE THREAD

**Issue by miyuchina** [v2ray/manual#58]
Hey there, I've noticed that the [documentation](https://github.com/v2ray/manual/blob/master/zh_cn/chapter_00/install.md) suggests the following command to execute installation script:

```sh
bash <(curl -L -s https://install.direct/go.sh)
```

Executing this command without `su root` in an ssh session yields the following error:

```sh
bash: /dev/fd/63: No such file or directory
```

I was able to bypass this error by running this command instead, still without switching to root user:

```sh
curl https://install.direct/go.sh | sudo bash
```

I was wondering if:

1. switching to root user is actually mandatory, as it seems to me only a user with sudo privileges suffices;
2. the second command is preferred over the first, since mine is a straightforward pipe from stdout, and does not need to create virtual files, which might (in my case) create problems over remote sessions.

Thanks for the project, and happy to open a pull request for this!

**Comment by Ariselia** [comment]
@miyuchina It has already announced that this command `bash <(curl -L -s https://install.direct/go.sh)`
should be execute under root.
> 以下指令假设已在 su 环境下，如果不是，请先运行 sudo su。
> The following command assumes root permission.

**Comment by miyuchina** [comment]
看到了，不过我想问的是是否一定需要 root 环境。

如果用我上述的命令，只需管理员账户用 sudo 运行即可。

感谢回复！

**Comment by DarienRaymond** [comment]
@miyuchina 当时测试过两种方式各有利弊，均在某些情况下不能使用。但是我已经忘了你的方式有什么问题。

**Comment by y0umu** [comment]
Maybe asking the user to download `go.sh` to a known location is better for debugging purposes?

```
curl -L -s -o go.sh https://install.direct/go.sh
bash go.sh
```
