### ISSUE TITLE
关于Wiki可能对于一些用户难以理解的几个建议(拙见)

### ISSUE THREAD

**Issue by StarryVoid** [v2ray/manual#77]
首先我的建议是认为wiki是给用户看的，如果是给开发者看的，当我没说，并且“请在WIKI上说明”
1、建议指明这部分配置的位置或者它所处的嵌套（从配置文件最开始的定位）
因为很多很多的wiki中的配置，仅仅是上面放个大括号，定位到完整配置文件中很难一次定位。
2、参数与参数之间的分隔符是逗号，建议说明一下
3、我有看到每个协议的配置，但是始终没有生成器生成的全面，于是这个能否补充完整？即使不解释每个参数的意义。
4、既然反馈群里每次都有人把https://github.com/KiriKira/vTemplate 发出来为什么不在wiki中体现呢？

**Comment by tleydxdy** [comment]
有关2，https://v2ray.com/chapter_02/

**Comment by StarryVoid** [comment]
我想我自己整个的整理了一次配置，就明白了各参数所属的位置。
感觉1，3，对于熟练配置的人来说似乎没什么意义了。。
先PR一下吧，不合适就close掉

**Comment by jellycsc** [comment]
刚开始开这个 doc 的时候确实觉得难懂，但是慢慢就看习惯了，其实内容是符合 JSON 逻辑的

**Comment by xianghongai** [comment]
我按照 /chapter_00/start.html 配置，没有成功。（能 ping 通服务器 ip 地址）

服务器 `vi /etc/v2ray/config.json` 后执行了：

> $ /usr/bin/v2ray/v2ray -test -config /etc/v2ray/config.json
> 
> V2Ray 4.22.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13.5 linux/amd64)
> A unified platform for anti-censorship.
> Configuration OK.
> 
> $ systemctl stop v2ray
> $ systemctl status v2ray
> $ systemctl start v2ray
> $ systemctl status v2ray
> 
> Loaded: loaded (/etc/systemd/system/v2ray.service; enabled; vendor preset: disabled)
>    Active: active (running) since Wed 2020-02-05 16:39:23 UTC; 2s ago
>  Main PID: 1899 (v2ray)
>     Tasks: 7 (limit: 2865)
>    Memory: 1.4M
>    CGroup: /system.slice/v2ray.service
>            └─1899 /usr/bin/v2ray/v2ray -config /etc/v2ray/config.json
> 
> Feb 05 16:39:23 vultrguest systemd[1]: Started V2Ray Service.
> Feb 05 16:39:23 vultrguest v2ray[1899]: V2Ray 4.22.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13.5 linux/amd64)
> Feb 05 16:39:23 vultrguest v2ray[1899]: A unified platform for anti-censorship.
> Feb 05 16:39:23 vultrguest v2ray[1899]: 2020/02/05 16:39:23 [Warning] v2ray.com/core: V2Ray 4.22.1 started


服务器应该是没有问题，

但是，客户端就是连接不上。

> 
> V2Ray 4.22.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13.5 windows/amd64)
> A unified platform for anti-censorship.
> 2020/02/06 00:40:07 [Warning] v2ray.com/core: V2Ray 4.22.1 started
> 2020/02/06 00:48:56 [Warning] [844009978] v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp **.**.**.**:18422: i/o timeout dial tcp **.**.**.**:18422: operation was canceled] > v2ray.com/core/common/retry: all retry attempts failed


建议 Wiki 部分，能做成较明确的、正确的说明，能按照 Wiki 跑起来。

**Comment by kslr** [comment]
安装指导类请移步到白话文教程中

**Comment by kslr** [comment]
白话文已经填补了针对普通用户的不足，因此我觉得这个issue可以关闭了
