### ISSUE TITLE
环境变量v2ray.ray.buffer.size描述有误

### ISSUE THREAD

**Issue by novoisland** [v2ray/manual#87]
https://github.com/v2ray/manual/blob/master/zh_cn/chapter_02/env.md

v2ray.ray.buffer.size描述与实际代码(v3.21  v2ray-core/transport/pipe/pipe.go)有区别，0应为禁止缓存，-1才是无上限

**Comment by DarienRaymond** [comment]
已修复，文档是不会改的。0表示无上限，不支持负数。

**Comment by novoisland** [comment]
谢谢，不过有点不明白pipe.go代码里WithoutSizeLimit的用途

**Comment by DarienRaymond** [comment]
以后会在Policy中增加相应设置
